@startuml
actor EMPLOYEE
participant View
participant ReleaseController
participant ReleaseSummaryResponseDTO
participant Release
participant ReleaseStatusUpdateService
participant ReleaseRepository
database Database

EMPLOYEE -> View : GET /releases/today/checked-out
View -> ReleaseController : GET /releases/today/checked-out
ReleaseController -> ReleaseStatusUpdateService : findAllTodayByCondominiumAndStatus(CHECKED_OUT)
ReleaseStatusUpdateService -> ReleaseRepository : findAllTodayByStatus(CHECKED_OUT)
ReleaseRepository -> Database : SELECT * FROM releases WHERE status = 'CHECKED_OUT' AND date = today
@enduml
